/**
 *
 * $Id$
 */
package type.validation;

import org.eclipse.emf.common.util.EList;

import type.EnumValue;

/**
 * A sample validator interface for {@link type.EnumListValue}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EnumListValueValidator {
	boolean validate();

	boolean validateValues(EList<EnumValue> value);
	boolean validateValue(EnumValue value);
}
