/**
 *
 * $Id$
 */
package featureModel.validation;

import featureModel.Attribute;
import featureModel.ComparisonOperator;
import featureModel.Feature;

import type.IntValue;

/**
 * A sample validator interface for {@link featureModel.Condition}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConditionValidator {
	boolean validate();

	boolean validateAttribute(Attribute value);
	boolean validateType(ComparisonOperator value);
	boolean validateValue(IntValue value);
	boolean validateFeature(Feature value);
}
